const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 5.4,
            numReview: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Sk Slim Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 120,
            brand: 'Nike',
            rating: 5.4,
            numReview: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'addidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 100,
            brand: 'addidas',
            rating: 4.0,
            numReview: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Lacosta Free pant',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 220,
            brand: 'Lacosta',
            rating: 5.0,
            numReview: 17,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Nike Slim pant',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 150,
            brand: 'Nike',
            rating: 5.5,
            numReview: 20,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Truma Slim pant',
            category: 'pants',
            image: '/images/p6.jpg',
            price: 50,
            brand: 'Truma',
            rating: 5.4,
            numReview: 50,
            description: 'high quality product',
        },
    ],
};
export default data;